<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php echo $this->getContent() ?>
<div class="container container--white container--border-side">
    <div class="page-header">
        <h1>Blog Posts</h1>
        <p>Some strapline<p>
    </div>
</div>

<div class="container container--wide">
    <div class="row container">

        <?php foreach ($page->items as $post): ?>
          <div class="small-12 large-4 columns">
            <a class="card" href="/blog/<?php echo $post->slug ?>">
                <img src="/images/car1.jpg" alt="<?php echo $post->title ?>" />
                <div class="card__text">
                    <h2 class="card__title"><?php echo $post->title ?></h2>
                    <hr />
                    <?php echo $post->content ?>
                </div>
            </a>
          </div>

        <?php endforeach; ?>
    </div>

</div>