<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("posts/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("posts/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Title</th>
            <th>Slug</th>
            <th>Content</th>
            <th>Created</th>
            <th>Users</th>
            <th>Categories</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $post): ?>
            <tr>
                <td><?php echo $post->id ?></td>
            <td><?php echo $post->title ?></td>
            <td><?php echo $post->slug ?></td>
            <td><?php echo $post->content ?></td>
            <td><?php echo $post->created ?></td>
            <td><?php echo $post->users_id ?></td>
            <td><?php echo $post->categories_id ?></td>

                <td><?php echo $this->tag->linkTo(array("posts/edit/" . $post->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("posts/delete/" . $post->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("posts/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("posts/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("posts/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("posts/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
